"""Deploy ready migrations

Revision ID: 65497c703b6c
Revises: e6c430b917c2
Create Date: 2025-03-19 07:14:03.206666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65497c703b6c'
down_revision = 'e6c430b917c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkout', schema=None) as batch_op:
        batch_op.drop_constraint('fk_checkout_inventory_id', type_='foreignkey')
        batch_op.drop_column('inventory_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inventory_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_checkout_inventory_id', 'inventory', ['inventory_id'], ['id'])

    # ### end Alembic commands ###
