"""Added category field to Inventory

Revision ID: 986ab5eea3b1
Revises: c5cbef6393ae
Create Date: 2025-03-15 08:50:53.035867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '986ab5eea3b1'
down_revision = 'c5cbef6393ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
